### ISSUE TITLE
height not same in youtube channel cards

### ISSUE THREAD

**Issue by dhruvdabhi101** [desaimann37/PortFolio.github.io#1]
<img width="919" alt="Screenshot 2023-01-30 at 12 27 46" src="https://user-images.githubusercontent.com/91935072/215408707-acfea03f-bd3a-4e5b-ab57-a99165738bff.png">

**Comment by desaimann37** [comment]
Thank u for pointing out Mr.Dabhi!!🥹

**Comment by dhruvdabhi101** [comment]
> Thank u for pointing out Mr.Dabhi!!🥹

Anytime @desaimann37 ☺️
